wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    code_path: code/project/training/run_experiment.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
dataset:
  desc: null
  value: EmnistDataset
experiment_group:
  desc: null
  value: Sample Experiments
gpu_ind:
  desc: null
  value:
  - 0
model:
  desc: null
  value: CharacterModel
network:
  desc: null
  value: mlp
network_args:
  desc: null
  value:
    num_layers: 4
train_args:
  desc: null
  value:
    batch_size: 256
    epochs: 16
